const players = [
  "Lionel Messi", "Cristiano Ronaldo", "Kylian Mbappé", "Erling Haaland", "Neymar Jr.",
  "Kevin De Bruyne", "Jude Bellingham", "Mohamed Salah", "Vinícius Jr.", "Robert Lewandowski",
  "Luka Modrić", "Toni Kroos", "Antoine Griezmann", "Karim Benzema", "Harry Kane",
  "Phil Foden", "Bukayo Saka", "Pedri", "Gavi", "Jamal Musiala",
  "Rafael Leão", "João Félix", "Marcus Rashford", "Martin Ødegaard", "Bernardo Silva",
  "Ilkay Gündogan", "Bruno Fernandes", "Declan Rice", "Eduardo Camavinga", "Aurélien Tchouaméni",
  "Frenkie de Jong", "Riyad Mahrez", "Sadio Mané", "Victor Osimhen", "Khvicha Kvaratskhelia",
  "Trent Alexander-Arnold", "Andrew Robertson", "Achraf Hakimi", "Theo Hernández", "João Cancelo",
  "Alphonso Davies", "Kyle Walker", "Antonio Rüdiger", "Éder Militão", "Virgil van Dijk",
  "Marquinhos", "Ronald Araújo", "William Saliba", "Matthijs de Ligt", "David Alaba",
  "Dayot Upamecano", "Jules Koundé", "Raphaël Varane", "Kalidou Koulibaly", "Cristian Romero",
  "Marc-André ter Stegen", "Thibaut Courtois", "Alisson Becker", "Ederson Moraes", "Mike Maignan",
  "Emiliano Martínez", "Yassine Bounou", "Gianluigi Donnarumma", "Manuel Neuer", "Jan Oblak",
  "Lautaro Martínez", "Ángel Di María", "Rodrygo Goes", "Gabriel Martinelli", "Richarlison",
  "Dusan Vlahović", "Alejandro Garnacho", "Ansu Fati", "Ferran Torres", "Rasmus Højlund",
  "Kai Havertz", "Christopher Nkunku", "Dominik Szoboszlai", "Cody Gakpo", "Yeremy Pino",
  "Ousmane Dembélé", "Federico Chiesa", "Nicolo Barella", "Sandro Tonali", "Manuel Ugarte",
  "Leandro Paredes", "Enzo Fernández", "James Maddison", "Declan Rice", "Nicolás González",
  "Álex Baena", "Takefusa Kubo", "Pau Torres", "Gonçalo Ramos", "Lucas Paquetá",
  "Warren Zaïre-Emery", "Xavi Simons", "Harvey Elliott", "Jérémy Doku", "João Neves"
];
